package releaseversion

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

// SyncMetadata updates only version fields, leaving application identity and
// unrelated XML dependency versions intact. All inputs are checked before writes.
// In check mode no files are changed.
func SyncMetadata(root string, v Version, check bool) error {
	type edit struct {
		path, pattern, value string
		count                int
	}
	display, numeric := v.String(), v.Windows()
	edits := []edit{
		{"Taskfile.yml", `(APP_VERSION: ")[^"]+`, display, 1},
		{"build/config.yml", `(?m)(^  version: ")[^"]+`, display, 1},
		{"frontend/package.json", `("version": ")[^"]+`, display, 1},
		{"frontend/src/product.ts", `(version: ")[^"]+`, display, 1},
		{"build/windows/nsis/wails_tools.nsh", `( !define INFO_PRODUCTVERSION ")[^"]+`, display, 1},
		{"build/windows/info.json", `("(?:file_version|product_version)": ")[^"]+`, numeric, 2},
		{"build/windows/info.json", `("(?:FileVersion|ProductVersion)": ")[^"]+`, display, 4},
		{"build/windows/wails.exe.manifest", `(name="io\.hypomux\.desktop" version=")[^"]+`, numeric, 1},
		{"build/windows/msix/template.xml", `(\bVersion=")[^"]+`, numeric, 1},
		{"build/windows/msix/app_manifest.xml", `(\bVersion=")[^"]+`, numeric, 1},
	}
	contents := map[string][]byte{}
	for _, e := range edits {
		data, ok := contents[e.path]
		if !ok {
			var err error
			data, err = os.ReadFile(filepath.Join(root, e.path))
			if err != nil {
				return err
			}
		}
		re := regexp.MustCompile(e.pattern)
		if len(re.FindAll(data, -1)) != e.count {
			return fmt.Errorf("unexpected version fields in %s", e.path)
		}
		contents[e.path] = re.ReplaceAll(data, []byte("${1}"+e.value))
	}
	contents["VERSION"] = []byte(display + "\n")
	contents["build/windows/nsis/version.nsh"] = []byte("; Generated by go run ./cmd/release-version -write. Do not edit by hand.\n!define INFO_PRODUCTVERSION \"" + display + "\"\n!define HYPOMUX_WINDOWS_VERSION \"" + numeric + "\"\n")
	for path, desired := range contents {
		actual, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			return err
		}
		if bytes.Equal(bytes.ReplaceAll(actual, []byte("\r\n"), []byte("\n")), bytes.ReplaceAll(desired, []byte("\r\n"), []byte("\n"))) {
			continue
		}
		if check {
			return fmt.Errorf("version metadata out of sync: %s; run go -C desktop run ./cmd/release-version -write", path)
		}
	}
	if check {
		return nil
	}
	for path, data := range contents {
		if err := os.WriteFile(filepath.Join(root, path), data, 0644); err != nil {
			return err
		}
	}
	return nil
}
